### ISSUE TITLE
New BSIP: Make the settlement offset vary with CR

### ISSUE THREAD

**Issue by shulthz** [bitshares/bsips#160]
```
BAIP: Draft
Title: Make the settlement offset vary with CR
Authors: 
Status: Draft
Type: Consensus 
Created: 2019-04-09
```

# Abstract

- Make the settlement offset vary with CR;

# Motivation

- Now the settlement offset is a fixed-parameter which can be changed by committee, the fixed-parameter can't adapt to the market changing,  especially effected by the feed price, this parameter too high is useless, too low is dangerous for the market, didn't have a suitable parameter.
- The settlement offset vary with CR will make the settlement more useful.
- The settlement offset vary with CR which can adjust the MCR through  the market, and can provide more controllability to the MCR when we  change the MCR to 1.5 or 1.6, the offset will control the risk by the market and make people to control their CR away MCR, also give the opportunity to the speculator who want a low CR in 1.5 or 1.6.
- The settlement will be a secondary the margin call, and it will be a market competition between the market participants, it is more flatter than margin call.
- And this can let the market themselves to prevent the extreme settlement events like 11/2017  Poloniex .

# Rational

# Specifications

```
K = Modification Factors（e.g 0.02）
x = Modification Factors（e.g. 3）

Force settlement offset= K*(CR/MCR)^x

```
1. CR above the MCR will get more settlement offset；
e.g.  
 when MCR=160 K=0.02,x=2,the 200% collateral ratio will get 3.1% Force settlement offset.
 when MCR=150 K=0.02,x=3,the 200% collateral ratio will get 3.9% Force settlement offset. 

```
# -- coding:utf-8 --

import matplotlib.pyplot as plt
import numpy as np

K=0.01
X=4
CR=np.arange(100,300)
MCR=160
offset=K*(CR/MCR)**X

plt.xlabel("CR",fontsize=15)
plt.ylabel("offset",fontsize=15)

plt.plot(CR,offset)
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/34892308/71301618-525faa80-23dc-11ea-8f47-7b16f5a0e397.png)

3.  If we need to set a Maximum settlement offset? maybe not;
4.  The settlement Delay above MCR still be 24 hours.

# Summary for holders

Make the settlement offset vary with CR can adjust the MCR through the market, and can provide more market controllability and competition. 
If the settlement offset affect the CR and make people to control their CR above the MCR?
If the market participants can take the risk to make a CR near the MCR which change to 1.6 or 1.5？
If this make the market more active？

# Discussion
https://bitsharestalk.org/index.php?topic=26762.msg319760#msg319760

# See also

# Copyright

This document is placed in the public domain.

**Comment by pmconrad** [comment]
Please elaborate why you think this would be a good idea. What is the effect you want to achieve and how do you expect the suggested changes to lead to the desired outcome?

IMO it complicates things further (and the market mechanics are already too complicated for many users). The numbers you suggest seem to be arbitrary, please give reasons for these choices. Or are you suggesting to make them configurable in some way?

**Comment by pmconrad** [comment]
Hm, I think the idea is worth considering.

A positive settlement offset means a reward for the short position. Since settlement happens against the least collateralized short, the short owner receives this reward for holding the least collateralized short. Obviously, incentivizing bad collateralization endangers the stability of the SmartCoin.

At the same time, we have used the settlement offset as a protective measure in case of skewed markets (particularly in the case of CNY). We do not want to lose this means. One option to remove the rewards for bad collateralization *and* keeping the protective effect would be to keep the settlement offset for the settler as-is, and reduce it for the short position depending on its CR. The delta could be paid into a pool belonging to the asset issuer.

**Comment by froooze** [comment]
@shulthz: You wanna make settlement for a bitAsset cheaper, when the least collateral level is lower?

**Comment by shulthz** [comment]
> 
> 
> @shulthz: You wanna make settlement for a bitAsset cheaper, when the least collateral level is lower?

YES, but still hava a Minimum settlement offset.

**Comment by xeroc** [comment]
Very nice idea!

**Comment by shulthz** [comment]
Unpublish post.

**Comment by shulthz** [comment]
Ask for a bsip number @sschiessl-bcp 
we can check biteur.

**Comment by abitmore** [comment]
Makes sense. Although raising the offset may push the trading price of the asset away from par value when devaluation occurs, on the other hand, it encourages traders to keep a certain supply of the asset (keep some liquidity).

> `offset=K*(CR/MCR)**X`

I think `K` and `X` need to be definable by the asset owners. Technically,
* `K` can be defined as a rational for the best flexity;
* `X` can only be an integer, otherwise it's hard to implement with current code base;
  * even it's an integer, it should be capped E.G. within `[-5,5]`, because we may need to implement it with the `*` operator with a loop, to not impact performance too much, should not loop too many times.

I wish we can find a better curve.

**Comment by shulthz** [comment]
> I wish we can find a better curve.

I'm not good at the code, you're the pro.
This is just an option, i just give some thoughts.
