### ISSUE TITLE
BSIP-0043 further improvements

### ISSUE THREAD

**Issue by bitfag** [bitshares/bsips#192]
Current implementation always rewards buyer of the asset (referrer and registrar) no matter was he `is_maker: True` or `False`. Instead, it would be more reasonable to always reward Maker.

Example (current): maker keeps sell order of 1000 CNY (order stays on books). When order fills, reward will go to buyer.
Proposed change: when order fills, the reward goes to Maker.

**Comment by abitmore** [comment]
The logic about market fee sharing is: the one who bought an amount of asset pays the market fee, her registrar and referrer would get a part of the fee. It's fair to reward the parties because they brought the trader who paid the fees. The logic was clear.

I don't think it's good to mix maker-taker incentives with market fee sharing incentives. For incentives about market makers, I think it's better to discuss in the scope of https://github.com/bitshares/bsips/issues/130.

**Comment by pmconrad** [comment]
> the one who bought an amount of asset pays the market fee

Clarification: in every trade there are two buyers, and *both* pay a market fee on the asset they buy (provided that the asset has a market fee set).

**Comment by pmconrad** [comment]
Agree that maker/taker fees are already discussed elsewhere. Closing this as a duplicate.
