### ISSUE TITLE
The intent of BSIP#5 is unclear

### ISSUE THREAD

**Issue by ThomasFreedman** [bitshares/bsips#2]
Whereas BSIPs 7 & 8 (I have yet to read all of them) are very detailed and comprehensive in their scope, BSIP 5  does not even provide an adequate description of the improvement, let alone the means to achieve it with adequate detail.

Best I can tell, this BSIP entails _changing voting characteristics_ for witnesses to provide an easier method for witness candidates to become active. Currently witnesses are elected into active duty via shareholder voting and witness campaigns to obtain those votes.

This BSIP lacks a minimal list of pros and cons to changing the existing witness governance model.

This BSIP lacks a description of the positive and negative impact to BitShareholders.

This BSIP also touches on the topic of reputation, but this must be fleshed out. What role should reputation play in witness qualifications, and how can that be established outside of performing witness duties? 

This BSIP also lacks a clear definition of witness qualifications and minimal standards of competency, as well as the specific criteria required to get voted into service or elected.

I am open to helping refine this BSIP but it currently lacks enough information about the desired effects and the author's intentions upon which to suggest changes.

**Comment by xeroc** [comment]
> Whereas BSIPs 7 & 8 (I have yet to read all of them) are very detailed and comprehensive in their scope, BSIP 5 does not even provide an adequate description of the improvement, let alone the means to achieve it with adequate detail.

> Best I can tell, this BSIP entails changing voting characteristics for witnesses to provide an easier method for witness candidates to become active. Currently witnesses are elected into active duty via shareholder voting and witness campaigns to obtain those votes.

Yes .. it's a quick *draft*

> This BSIP lacks a minimal list of pros and cons to changing the existing witness governance model.
> This BSIP lacks a description of the positive and negative impact to BitShareholders.

I totally agree .. let's collect the pros and cons.

> This BSIP also touches on the topic of reputation, but this must be fleshed out. What role should reputation play in witness qualifications, and how can that be established outside of performing witness duties? 

Witnesses need to be *trusted*. That's why reputation *may* play a role. But in the end, it's the shareholders individual decision to make. 

> This BSIP also lacks a clear definition of witness qualifications and minimal standards of competency, as well as the specific criteria required to get voted into service or elected.

Agreed. Could you add your points into the BSIP and send a pull request?

> I am open to helping refine this BSIP but it currently lacks enough information about the desired effects and the author's intentions upon which to suggest changes.

My intension was to collect all ideas that are currently "open" and put them into a document. Those are meant as drafts and are FAR from being complete (all of them). But at least we now have a framework to put stuff together and produce informative documents for the shareholders. That's the main purpose: Give shareholders a document that they can read to make a decision.

But I understand that there is much work needed to reach that goal!

**Comment by ThomasFreedman** [comment]
Shouldn't a BSIP be at a much further state of maturity before it's submitted here? I don't feel the ideas behind this proposal have been discussed very much in the forum (certainly not recently), nor are they explained very well as a starting point in the BSIP itself. IMO this proposal is does not rise to the *minimum* standards we should have for BSIPs. I also firmly believe this should be an *Informational* BSIP not a *Protocol* type BSIP.

I have been thinking a great deal about how to strengthen the witness role since reading this. Because so much of the DPoS model relies on this role, it needs much thought and scrutiny. After rereading the abstract and motivation sections I am very much opposed to the concept of coercing changes by manipulating shareholder votes as a means of addressing voter apathy. It is a patch to address a more fundamental problem and forces shareholders to continually re-express their voting preferences. If this approach is so good why limit it only to votes for witnesses? Why not for **all** votes?

Voting proxies are one solution to the problem expressed herein. If a shareholder does not wish to be involved proactively they may designate a proxy who is. If no proxy is set and thus that shareholder's interests are not expressed, maintenance of the ecosystem falls to the committee or those shareholders which are more active, either directly or via their designated proxies.

I do recognize the issue of voter apathy is an extremely important issue to the viability of the DPoS governance model. The bottom line however is that if apathy prevails shareholders will get the ecosystem leadership that does not directly reflect their interests, if at all. Rather than use the heavy handed, knee jerk reaction of oligarchical control, my perspective is that a better understanding of the witness role through more thorough documentation and standards will be better for the health and well being of our DPoS ecosystem. 

In fact, for such fundamental issues as those that impact the DPoS model such as voting, I feel a higher standard of consensus is warranted. Without that, governance will be seen as too centralized. The idea here is like when a simple majority is required vs a two thirds majority, for example when an amendment the U.S. Constitution is proposed it requires a substantially higher level of consensus. 

In the same way some BSIPs should require a higher level of consensus. A two thirds majority of the voting stake may not be achievable now, tho perhaps each BSIP should provide a target consensus metric to indicate its importance as well as threshold of approval.

May I suggest we table discussion of this topic here and explore it more deeply and informally in the forums, leaving this venue for discussion / refinement of details rather than the broad foundations which underlay this proposal. I will start a forum thread in the "Shareholder Proposal" / witness section and cross link it here.

The post will focus on these areas:
1) The issues (voter apathy, lack of fresh witnesses, stability, incumbent witness accountability)
2) Considerations (reputation, technical abilities, ecosystem knowledge, conflicts of interest)
3) Candidate process (mentoring / training, accomplishments, voting campaigns, motivation)
4) Policies (metrics for monitoring witness performance, decentralization, anonymity, feeds, communications, grounds for termination, process for termination, minimum vote threshold, minimum technical standards)
5) Standards and best practices (some of these overlap with items above)

That's a lot of information to cover! Now that I've outlined all I can think of about the witness role, I think I need to you (xeroc, BM) to elaborate more on the perceived problem and why you think expiring votes will strengthen the witness role or help to resolve voter apathy. At least provide some thought into the pros and cons to the ecosystem. Xeroc, speaking of standards, perhaps you should consider amending your *BSIP Purpose and Guidelines" by adding a "Minimum BSIP Requirements" section following the "What Belongs in a BSIP" to narrow the scope and focus discussion. 

This venue should NOT be treated as a loose, informal discussion like the forum. To that end, every BSIP listed here should contain a minimal set of requirements. IMO the originator of the BSIP should at least provide Pros and Cons of the proposal which demonstrate sufficient thought has gone into it and the effects it will have on the ecosystem. Perhaps other minimums should also be explicitly listed in this section.

I recognize this very post goes beyond a formal discussion of this BSIP's merits, but until standards are established to limit the discussion here such long winded responses may be common.

**Comment by bytemaster** [comment]
I had a brief thought on voting with respect to the "security" vs "rapid change" debate.  Namely, that witnesses and/or committee members should be weighted on an average vote over a period of time (say 1 week or 1 month) and not an instantaneous vote.  This will help prevent an attacker from suddenly changing the witnesses without waiting for the averages to kick in.  In other words, this gives a review period.

With respect to expiring votes, it should be a linear function over 1 year. If the goal is to use percent of voting stake as the measure of consensus then there needs to be some way of keeping votes fresh or else the network could get "stuck".  As people come and go from being "active" it will create a ratchet effect where stale votes cause the 51% threshold to become more like 80% because 30% are stale and will never support something.  

Also, I don't think we need to have any particular threshold because of the "positive/negative" voting. Any net positive vote indicates that the support is greater than the resistance even with very low participation.

**Comment by xeroc** [comment]
> Shouldn't a BSIP be at a much further state of maturity before it's submitted here? I don't feel the ideas behind this proposal have been discussed very much in the forum (certainly not recently), nor are they explained very well as a starting point in the BSIP itself. IMO this proposal is does not rise to the minimum standards we should have for BSIPs. I also firmly believe this should be an Informational BSIP not a Protocol type BSIP.

I agree with you. Should it be rejected, withdrawn or stay in *draft*? At least a new discussion has started

> In the same way some BSIPs should require a higher level of consensus. A two thirds majority of the voting stake may not be achievable now, tho perhaps each BSIP should provide a target consensus metric to indicate its importance as well as threshold of approval.

The idea for shareholder voted hard forks on the chain (as part of the protocol) has not been finalized yet. But IIRC @bytemaster proposed to require every hardfork to have AT LEAST as many votes as the burn/refund worker (@bytemaster: btw, how should we handle several burn/refund workers then?)
Hence, refund/burn workers indicate the required threshold. Would that be ok for you?
Requiring 3/4 will make us stuck in not improving at all (voter apathy) so we should related to 'active stake' instead




> I had a brief thought on voting with respect to the "security" vs "rapid change" debate. Namely, that witnesses and/or committee members should be weighted on an average vote over a period of time (say 1 week or 1 month) and not an instantaneous vote. This will help prevent an attacker from suddenly changing the witnesses without waiting for the averages to kick in. In other words, this gives a review period.

An issue is that you can't quickly fire misbehaving witnesses (on the otherhand, however, no one can easily replace the witnesses without giving notice.)


> With respect to expiring votes, it should be a linear function over 1 year. If the goal is to use percent of voting stake as the measure of consensus then there needs to be some way of keeping votes fresh or else the network could get "stuck". As people come and go from being "active" it will create a ratchet effect where stale votes cause the 51% threshold to become more like 80% because 30% are stale and will never support something.

A one year period sounds o.k. to me. Considering that in the end voting power is probably mostly controlled by proxies that are active in the network in some sense, I would hope they refresh the votes once every few months.

**Comment by ThomasFreedman** [comment]
Comments below in red large font.

**Comment by xeroc** [comment]
> IMO it should be rejected until a minimum standard of info is provided.
Although a case can be made that minimal standard is not (yet?) in the
guidelines. I just feel there's not much use for yet another loose, informal
discussion platform where all we gain is github revision tracking. I think it
needs to be a tighter, professional standard akin to a standards body like IETF
or IEEE proceedings.

Agreed. However, I feel that the forum is really not well suited for proper
discussion of an innovation *on a technical* basis. Having a central document
that can be worked on is what we need IMHO. However, I agree that we need a
professional standard and we should build one and we can use existing ideas to
form and develop this standard (e.g. using bsip-0001).


> I agree, if we set the threshold too high approval may not reach the required
threshold. Yet the concept of including a consensus threshold and associated
metric within the proposal is valid, and allows the proposer to convey his / her
perspective of the importance of the proposal. It's just one more level of
thought process and a way to tighten up the formality. Perhaps the guidelines
could provide some basic consensus metrics, categories in terms of a range, like
"normal" (same as current policy), "emergency" (specific conditions for relaxed
approval, or minimal approval), "high priority" etc. As how the burn/refund
worker fits into consensus I don't understand at all. Is that an unnecessary
complication? If not, perhaps it's ramifications and the pros and cons of it
could be explained in the proposal.

I agree. Let's unlink the governance from burn/refund workers and try to
establish a consensus about "threshold(s)". What is important is that at the end,
we have a binary decision: Will the blockchain upgrade to integrate this
proposal in a hard fork or not? I don't reall see the need for several
categories for different thresholds. Instead, I would propose to have a
threshold be defined by shareholders directly. Why not have a 0-pay worker
proposal that people can vote on. If a proposal reaches more votes than the
threshold worker, it is accepted, if not (in a timely mannger, *tbd*), it will
be rejected. This way, shareholders can vote to have a never changing blockchain
by putting all their votes on the threshold 0-pay worker.



> Yes, I share those concerns. I was not very happy with the 2.0 announcement
concerning vote tallying on a less frequent (i.e. maintenance window) basis.
However performance dictated vote compilation less frequently so it was a
necessary tradeoff. In general I believe the entire subject of "witness
management / policies" needs more focus and care than it has been given, and I
see this BSIP as a quick fix that should not be pushed through without far more
scrutiny. 

Agreed. I'll set it to "deferred".
we should first see what happens if we increase the maintenance interval. That
at least prevents *rapid changes*.

> I provided many elements to be considered in my github comments but
have seen almost no feedback related to that. I'm sure there are tradeoffs to
consider, but we need the policies to strike a balance between stability (i.e.
harder to remove, reputation basis) and security against attack or sudden
changes (ability to quickly remove threatening witnesses). THIS IS A CORE DPoS
GOVERNANCE ISSUE.

Agreed. Do you have a recommendation how to tackle that issue?



> Perhaps. I think the ramifications need to be spelled out clearly through a
few pro and con scenarios. I do agree that proxies can change the dynamics
entirely tho, and that is another potential attach vector. It may be a costly
one, depending on the goal of the attacker. In the end even using proxies
doesn't circumvent the need for a large stake to directly effect change, but it
could play a significant role in influencing others that do have a large stake.
If a potential smooth talking proxy is able thru deception to get enough stake
concentrated in his proxy, that could be very bad. How can a "bad actor" proxy
be removed and what conditions must be met to do so?

Bad actor proxies cannot be removed. You can only ask/convince shareholders to
remove him as proxy.

**Comment by grctest** [comment]
I support BSIP #5 because people eventually die (grim but a reality) & their votes will otherwise be permanent. We don't want proxies or witnesses permanently in power..

**Comment by abitmore** [comment]
Stale.
