### ISSUE TITLE
Smartcoin Design Improvement

### ISSUE THREAD

**Issue by clayop** [bitshares/bsips#21]
While Smartcoins are powerful with its stability, its mechanism is flawed against the issuers. More specifically, issuers only benefit when BTS price is rising, regardless of popularity of Smartcoins (e.g. large number of transactions per day). Meanwhile, profits generated from using Smartcoins via fees are diluted to the whole network and this yields the free-rider problem.

My proposal is basically to directly benefit the issuers when Smartcoins are used. This will make another profit source in addition to BTS price change. More specifically, my suggestion is:

Divide fees from using Smartcoins (e.g. transfer fee) into the network and the issuers (currently 100% goes to the network and be burnt). When 100% goes to issuer, there would be an attacking vector to spam the network.
If fees are paid in BTS, add them to a Smartcoin's collateral pool so the issuers can return more when they clear debt.
If fees are paid in a Smartcoin, reduce the debt pool so each issuer have less debt.
By doing so, businesses using Smartcoins are more incentivized to issue and facilitate using Smartcoins, and when issuing Smartcoins become profitable regardless of BTS price (e.g. profits from fees exceeds losses from BTS price fall) more people are willing to issue Smartcoins, and consequently more BTS is locked and will start the virtuous circle.

**Comment by xeroc** [comment]
Another proposal: how about we ask for a trading fee on the bitasset (bitUSD) and let those fees be distributed to the collateral holders?

Drawback is .. you never know if someone is really 'short' or just borrowed the bitasset and letting it sit in his own account ..

**Comment by clayop** [comment]
That can be broader application of the original proposal. I thought it as well but didn't arranged my ideas. But sounds good too.

**Comment by rngl4b** [comment]
I have no finantial background to to see its real potential or drawbacks, but in general terms I like this approach. If we get to an agreement, we could shape most issuance and trading incentive proposals just adding the basic smartcoin flags and bitasset parameters needed by users to find both network and own sweetspots.

**Comment by abitmore** [comment]
Another approach would be: smartcoin holders pay interest to short position holders. However, any mechanism that taxes Smartcoin holders will more or less harm adoption.

In regards to implementation, it won't scale if directly distributing cents of fees and/or interests after each transaction among many holders. So they should be implemented as a pool which pays out periodically, weighted by coin-seconds.

**Comment by clayop** [comment]
Good point @abitmore. So collected fees should go the collateral "pool" first, to avoid decimal issues.

Regarding numbers, my personal preference is 10% goes to the network and 90% goes to the issuers (Non LTM case). If LTM, 50:50 (So the total network fee is the same as non LTM)

**Comment by jiefangqian** [comment]
We can have a look Ripple's update:
Problem & Solution

Currently, offers on RCL can differ by as little as one part in a quadrillion. This means that there is essentially no value to placing an offer early, as an offer placed later at a microscopically better price gets priority over it. The TickSize Amendment solves this problem by introducing a minimum tick size that a price must move for an offer to be considered to be at a better price. The tick size is controlled by the issuers of the assets involved.

When you place a buy offer, the amount of currency you will buy is respected. When you place a sell offer, the amount of currency you will sell is respected. If a tick size is in force, the other side of the offer will be rounded (in your favor) such that the ratio is rounded to the tick size before the offer is placed on the books.

TickSize does not affect the size of an offer. A trader can still trade microscopic amounts of an asset. It just affects the prices (ratio of in to out) at which offers can be placed on the books. For asset pairs with XRP, the tick size imposed, if any, is the tick size of the issuer of the non-XRP asset. For asset pairs without XRP, the tick size imposed, if any, is the smaller of the two issuer’s configured tick sizes.

The tick size is imposed by rounding the offer quality down to the nearest tick and recomputing the non-critical side of the offer. For a buy, the amount offered is rounded down. For a sell, the amount charged is rounded up.

Effects of TickSize Change

This change lets issuers quantize the exchange rates of offers to use a specified number of significant digits. Gateways must enable a TickSize on their account for this feature to benefit them. A single AccountSet transaction may set a “TickSize” parameter. Legal values are 0 and 3-15 inclusive. Zero removes the setting. 3-15 allow that many decimal digits of precision in the pricing of offers for assets issued by this account. It will still be possible to place an offer to buy or sell any amount of an asset and the offer will still keep that amount as exactly as it does now. If an offer involves two assets that each have a tick size, the smaller number of significant figures (larger ticks) controls.

Benefits of TickSize Change

The primary expected benefits of the TickSize amendment is the reduction of bots fighting over the tip of the order book, which means:

Quicker price discovery
Traders can’t be outbid by a microscopic amount
More offers left on the books
A reduction in offer creation and cancellation spam
We also expect larger tick sizes to benefit market makers in the following ways:

They increase the delta between the fair market value and the trade price, ultimately reducing spreads
They prevent market makers from consuming each other’s offers due to slight changes in perceived fair market value, which promotes liquidity
They promote faster price discovery since traders have to adjust their prices in financially distinct increments
They reduce transaction spam by reducing fighting over the tip of the order book and reducing the need to change offers due to slight price changes
They reduce ledger churn and metadata sizes by reducing the number of indexes each order book must have
They allow the order book as presented to traders to better reflect the actual book since these presentations are inevitably aggregated into ticks
https://ripple.com/dev-blog/rippled-0-50-0/

**Comment by bitcrab** [comment]
I don't think the suggestion will help.

Smartcoin is a leverage tool, it makes sense not only when BTS price rise. it enable shorters to borrow money and buy other assets, for example BTC,  shorters can also make profit if he borrow smartcoin to buy BTC at lower BTC price and sell BTC to close smartcoin debt position at higher BTC price.

if there is no more smartcoin usage, just encourage shorting makes no sense, the supply of bitCNY has reached 2M, why? because every shorter can borrow bitCNY and then withdraw to outside DEX via transwiser, so finally more than 1M bitCNY accumulated in transwiser and I have to forcesettle about 1M. - so if now anyone ask me "is 1M bitCNY enough in Bitshares?" I will say, "Yes, it is enough for current usage, if anyone need bitCNY please contact me, I can sell 200-300K bitCNY to him."

taxes to holders or shorter bonus will all reflect in the price of smartcoin, so whether to build the taxes/bonus make no big difference, however, they bring big complexity to make the machanism more difficult to understand, and may bring new problems.

**Comment by ThomasFreedman** [comment]
> If fees are paid in BTS, add them to a Smartcoin's collateral pool...

I like that as opposed to xeroc's suggestion they be paid to owner's of the collateral. The distinction being if paid into collateral it strengthens the BitAsset against falling BTS price instead of it not being locked up for the BitAsset holder to do with as they please. 

However, the scaling issue is also an important consideration which abit raises. Assuming all buyers of BitAssets do indeed pool the collateral I think periodic payouts from a "dividends" pool is a good solution to the scaling / rounding problem. If the collateral each buyer of a BitAsset has to provide is not pooled but rather tracked individually then a pooled payout of dividends would result in collectivizing rewards rather than having them be attributed to each BitAsset holder individually. 

That may or may not be a concern, I don't know.

**Comment by clayop** [comment]
@bitcrab Thanks for sharing your opinion. The problem I am attempting to solve is discrepancy between risks and returns in shorting (issuing) Smartcoins. When an issuer create Smartcoins by shorting, he will be exposed to BTS price and all accompanied benefits/losses, which is totally fair. However, profits(a.k.a. fees) from using utilities of Smartcoin, mainly stability thanks to over 1.5x collateral from the issuer, goes to the network and benefit all stakeholders. In BitCNY's case, its issuers only benefit approximately 14% of total profit (because the market cap of BitCNY is about 14% of BitShares'), and other 86% is distributed to mere BTS holders who don't expose them to the risk.

This is the main problem this proposal is trying to tackle. It doesn't change strategy what you mentioned, and just give additional incentives to the issuers.

**Comment by pmconrad** [comment]
I think the general idea of rewarding shorters is good. However, like xeroc pointed out, any BTS holder can easily reap those rewards by creating smartcoins and keeping them. It's risk-free if managed properly, because the shorter can always close his position at virtually no cost.

On the technical side, there is no global "debt pool" nor "collateral pool". There are only individual pools, one for each shorter. That would make it quite costly to pay out the collected fees to all shorters.

**Comment by clayop** [comment]
@pmconrad Thanks for your input, especially technical sides.

Regarding you and xeroc's concern, it surely can happen. However, I also want to point out that it's not 100% risk-free because BTS holders are exposed to BTS price. So even though they want to free-ride on profits from Smartcoin transactions, they unintentionally increase BTS demand.

**Comment by grctest** [comment]
If we can prevent the old 'yield-harvesting' issue that 'socialized yield' was vulnerable to, then perhaps this would be feasible. I have brought up the idea of targeting market-makers for receiving UIA sharedrops [in my bsip 20 draft](https://steemit.com/bitshares/@cm-steem/bsip-020-draft-introducing-profit-sharing-dividends-to-bitshares-uia-only-input-would-be-massively-appreciated), though as an user pointed out it would require these market maker statistics to be more readily accessible within the client to be implemented. That said, an external script could probably figure these values out & create a manual sharedrop against market makers..

**Comment by abitmore** [comment]
Stale.
