### ISSUE TITLE
For better marketing, find another name for "Tanks and Taps"

### ISSUE THREAD

**Issue by abitmore** [bitshares/bsips#252]
The name "Tanks and Taps" just sounds unattractive to me. I think we need a better name if we want to market it.

**Comment by sschiessl-bcp** [comment]
I do like the name though. For internal marketing the name is not that relevant IMHO, so we can re-discuss this if BTS holders accept it.

**Comment by litepresence** [comment]
Percent Allocation Management Module (PAMM) is a well known term in the financial industry.  

TNT + custom active authorities makes PAMM possible.   My suggestion is that script be provided to leverage TNT+CAA into PAMM contracts and marketing focus on the well known PAMM construct rather than the underlying technology of TNT + CAA.
