### ISSUE TITLE
The second level  collateral is an open idea .

### ISSUE THREAD

**Issue by ebit116** [bitshares/bsips#78]
The shorter has the freedom to choice settlement time or call price .
If he has the second level collateral ,such as gdex.btc open.btc . 
Then,we have no reason to buy bitcny for adjusting.

BTS's value come from market,gdex.btc or open.btc 's value come from market too .
Nobody question bitcny's value ,but it is too scarce .
So ,may be ,we could hold bitcny by more collateral.

**Comment by shulthz** [comment]
gdex.btc or open.btc is not based on the Bitshares's DEX core Assets，it based on the GDEX or OPEN gateway service.

I don't think it's suitable or good as the collateral.

BTS is not like the MakerDAO which can use ERC20 TOKENS as the collateral.

**Comment by abitmore** [comment]
The system allows people to create a new CNY type e.g. GDEXBACKED.CNY backed by GDEX.BTC, but it's another asset, not the "bitCNY" backed by BTS.

**Comment by jiefangqian** [comment]
The second collateral is not used to create bitcny ,its mission is a certificate. 
When I will be settlement.
If gdex.btc as the second collateral,I can down my call price with it.
Otherwise before that i must sell gdex.btc for settlement.
Asset sell wall is a double hurt for BitshareS system,when  BTS was dumped.

**Comment by pmconrad** [comment]
The idea of backing Smartcoins with multiple types of collateral is also being discussed in #100 (if that's what this here is about). Closing.
